### ISSUE TITLE
add value twice through "addable" option

### ISSUE THREAD

**Issue by yusuke50** [brianvoe/slim-select#21] opened 2017-12-15 06:05 UTC
Hi,

I love this plugin, it fits my require for multiselect.
But the value will add twice when I add value through "addable" option. There is an issue #12 already.
Can you help for this issue? Thank you so much.

**Comment by brianvoe** [comment] 2017-12-15 15:45
Are you referring to a multi select? Cause i think ive seen that too. Ill look into more and see if i can find something. If you have looked at the code i would be more than happy to hear if you see something obvious.

**Comment by brianvoe** [comment] 2017-12-15 15:58
Ok i see it now. I was able to recreate it. So just in case you were worried, it is just a display issue. the actual selected values do not duplicate. Ill get this fixed as soon as i can.

**Comment by yusuke50** [comment] 2017-12-16 01:37
Yes, this issue happened to a multi select. 

Thanks for reply.

**Comment by asasinuxp** [comment] 2017-12-28 17:17
Hello,

I had a similar problem when setting the selected values using the "set" method. One of the options appeared to be selected twice.
For me this was fixed by setting the values only after the DOMContentLoaded event is fired.

I hope this might help other people having the same issue.
Have a nice day :)

**Comment by brianvoe** [comment] 2017-12-28 20:17
Thanks. Im currently making adjustments to address these things ill keep everyone up to date when its done.

**Comment by macfire** [comment] 2018-03-10 23:34
Is this issue still on your radar?

**Comment by brianvoe** [comment] 2018-03-10 23:54
Its fixed for now. I left if open cause i want to tackle a different way of fixing this issue. But for now it should work as is.

**Comment by macfire** [comment] 2018-03-11 00:25
I just tried v1.11.1 and am still encountering same issue.
I'm using `setData` to set the options.

```javascript
var ss = new SlimSelect( { select: "#my_selectfield" });
ss.setData(my_data);
```

**Comment by brianvoe** [comment] 2018-03-11 03:19
ok if thats the case can you do ss.render() and see if that resolves it? If so then i know where the issue is.

**Comment by yusuke50** [comment] 2018-03-11 03:36
Hello, 

I created the <select> in HTML file, then bound SlimSelect when init(). 
The options in multi-select are displayed correctly in 1.11.1, thank you for fixing.

**Comment by brianvoe** [comment] 2018-03-11 04:26
no problem. glad it was resolved for you.

**Comment by macfire** [comment] 2018-03-13 16:34
@brianvoe 
Calling `ss.render()` after `ss.setData(my_data)` did not work for me.

```javascript
var ss = new SlimSelect( { select: "#my_selectfield" });
ss.setData(my_data);
ss.render();
```
For now, I can work around by rendering the <options> nodes in the DOM first, then call new SlimSelect without calling `setData()`.

**Comment by brianvoe** [comment] 2018-03-13 16:44
Ok thanks for trying that ill get to bottom of why that isnt working.

**Comment by brianvoe** [comment] 2018-03-13 19:56
Ok i believe i tackled this. Had to do with looping through nodes that needed to be deleted. cant delete a node while also looping through it at the same time. this should be fixed and live. v1.11.2

npm install this new version and let me know if this works for you.

Thanks everyone who noticed it and helped me pin point the issue. Its people like you that help make these packages the best they can be. Great work!

**Closed** 2018-03-14 14:40 UTC
Labels: bug

**Comment by tomerb15** [comment] 2018-03-27 13:02
JUST IN CASE:
It happen to me as well when using ss.setData(arrayOfObjects) with an array that has several object with the same `text` prop while the `value` is unique.

Also Maybe related: The select element was inside a bootstrap modal.

My fix was:
```
ss.setData(arrayOfObjects);
setTimeout(function(){ss.render()},200);
```
