### ISSUE TITLE
Dropdown closes when search box gets user focus [Safari]

### ISSUE THREAD

**Issue by iclang** [brianvoe/slim-select#156] opened 2019-07-22 19:22 UTC
In Safari, (Mac or iOS) when the dropdown is open it focuses on the search input as expected, but if you then click on the input box it closes the dropdown. 

Thought this was because of customization but I've stripped out all of my own code and believe this might be a bug in 1.23.0.

https://codepen.io/clang/full/BXoEjO

Is this a bug or am I overlooking something?

Thank you!

**Comment by LennyKiano** [comment] 2019-09-08 10:40
I am facing the same issue as well. I'm using slimSelect on a polymer 3.0 project for work and when the search input is clicked it closes the dropdown.

**Comment by brianvoe** [comment] 2019-09-09 16:29
I see the issue is safari specific. Not sure why safari is acting differently. I would be more than happy to make any updates or adjustments to fix this for safari.

Just to give you guys some context Slim Select has a window event click on it and if where you click is within the dom element of slim select, of so it will not close it. https://github.com/brianvoe/slim-select/blob/master/src/slim-select/helper.ts#L1

If either one of you want to figure out why this doesnt work in safari ill implement any changes needed to fix it.

**Comment by LennyKiano** [comment] 2019-09-10 04:07
![fixed search input click](https://user-images.githubusercontent.com/31030432/64583287-21adb500-d399-11e9-9663-806f1961d7c0.jpg)
For my case in polymer I have to reference the shadowRoot, so I prevented the search input from closing when it is clicked by adding an 'click' event listener and calling `event.stopPropagation()` as shown above

**Comment by brianvoe** [comment] 2019-09-10 15:22
I could try that in slim select and see what happens

**Comment by iclang** [comment] 2020-02-07 20:00
Hey @brianvoe, did you have a chance to try out Lenny's suggestion? Curious on the results or if it was addressed in other ways?

**Comment by brianvoe** [comment] 2022-11-21 01:49
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.

**Closed by brianvoe** 2022-11-21 01:49 UTC
